### PR TITLE
liberties

### PR DESCRIPTION
**Pull request by ungoldman**
I have... taken liberties with your repository, Nikolas. I wished to see what you were up to.

I replaced the `credentials.json` gambit with [`ghauth`](https://github.com/rvagg/ghauth) -- on first run, it will prompt for credentials, create an oauth token, then never bother you again. Works with 2FA too. No more username and password in plaintext.

I also moved things around so that requests to github are sequential.

Right now it's outputting quite a lot of text -- for example running `npm start | wc -l`, I get 421830 lines (`npm start` now runs `node index.js`).

I think I see where you're headed with this one and would like to see more, so I thought I'd do a thing or two to help out.

### CODE REVIEW

**Comment by ngoldman** [comment]
P.S. congratulations, you are my 1,000th star.

:tada: :tada: :tada: :tada: :tada: :tada: :tada:
:tada: :tada: :tada: :tada: :tada: :tada: :tada:
:tada: :tada: :tada: :tada: :tada: :tada: :tada:
:tada: :tada: screen shot 2016-03-01 at 10 37 53 pm :tada: :tada:
:tada: :tada: :tada: :tada: :tada: :tada: :tada:
:tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Comment by ungoldman** [comment]
@nikolaswise can we please have a conference call about this? I'd like to loop in some more people.

**Comment by ungoldman** [comment]
I've looped in @paulcpederson.

**Comment by nikolaswise** [comment]
@ungoldman I'm scheduling a kickoff meeting pre-meeting to loop in the stakeholders who will need to hold the steaks on this one. Look for my outline invite via lync

**Comment by ungoldman** [comment]
Slow your roll there @nikolaswise, I think we need more eyes on this before we send out any invites. Maybe @paulcpederson can help us with at least one solid deck to really get the vision across to the design manager, and the product engineer, and the product designer, and the engineer manager, and the management designer before we go full hog on the steakholders meating.

**Comment by ungoldman** [comment]
I think skype would be more appropriate at this juncture.

**Comment by nikolaswise** [comment]
Why isn't there a barfing emoji?

Anyway, glad you think this is cool! Will for sure flesh it out.

**Comment by ungoldman** [comment]
Just gonna leave this here https://www.google.com/search?q=barf+emoji&safe=off&tbm=isch

**Comment by nikolaswise** [comment]
also lol 'management designer'

**Pull request merged**
